### ISSUE TITLE
Highlighting stops if there's a ? in the query parameter

### ISSUE THREAD

**Issue by JoshuaWi** [themashcodee/url-highlighter-vscode-extension#1]
Using the highlighter stops if one of the query parameters is a `dest`  or equivalent in which a path with new query parameters is contained.

For example
`https://someurl.com?param1=something&dest=some/path/with/params?parameter=something`

**Comment by themashcodee** [comment]
Hey @JoshuaWi 

If you would like to solve this issue and contibute to the project you are most welcome, I would highly appreciate that. Otherwise I will fix this issue on this weekend!

Thanks for reporting!

**Comment by themashcodee** [comment]
@JoshuaWi It is fixed 🚑
